name: harpo
description: A Dart package for numeric encryption/decryption and binary & hexadecimal encryption/decryption!
version: 2.3.0
homepage: https://github.com/angeldollface/harpo
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  pedantic: ^1.11.0
